version: "3"

networks:
  elkkweb-net:

services:

  postgres:
    image: gbtmago/datomic-postgres
    build:
      context: .
      dockerfile: dockerfiles/datomic-postgres.dockerfile
    networks:
      - elkkweb-net
    volumes:
      - /var/data/db/postgres/data:/var/data/db/postgres/data

  datomic:
    image: gbtmago/datomic
    build:
      context: .
      dockerfile: dockerfiles/datomic-pro.dockerfile
    depends_on:
      - "postgres"
    networks:
      - elkkweb-net
    volumes:
      - /var/data/db/datomic/data:/var/data/db/datomic/data

  elkkweb:
    image: gbtmago/elkkweb
    build:
      context: .
    depends_on:
      - "postgres"
      - "datomic"
    ports:
      - "443:443"
      - "80:3003"
    networks:
      - elkkweb-net
    volumes:
      - /var/data/www/elkkweb:/var/data/www/elkkweb
